apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventease-argo-application
  namespace: argocd
  # delete resources when argo is stopped
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # Tracked repo
  source:
    repoURL: https://github.com/omarade/EventEase-IAC
    # Last commit
    targetRevision: HEAD
    # K8S config folder
    path: K8S
  destination:
    server: https://kubernetes.default.svc
    namespace: eventease

  # Argocd policies
  syncPolicy:
    # Create destination namespace if it does not exist
    syncOptions:
    - CreateNamespace=true

    automated:
      # Automatic self-healing (undo manual changes to the cluster & resync with repo state)
      selfHeal: true
      # Automatic pruning (when a yaml file is deleted it will be deleted from the cluster as well)
      prune: true