apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: oaddev/authservice:eacc0e9f2fae476a75c639643ce99e7a466b9f85
        env:
          - name: RABBIT_MQ
            valueFrom:
              secretKeyRef:
                name: rabbit-mq-secret
                key: rabbit-mq
          - name: JWT
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwt
          - name: AUTH_DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: auth-db-secret
                key: db-connection-str
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: authservice
  ports:
  - name: authservice
    protocol: TCP
    port: 80
    targetPort: 80
