apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  # namespace: eventease
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: oaddev/authservice:fd3622e41339e7309bdb4779eb456cb1919b522e
        env:
          - name: RABBIT_MQ
            valueFrom:
              secretKeyRef:
                name: rabbit-mq-secret
                key: rabbit-mq
          - name: JWT
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwt
          - name: AUTH_DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: auth-db-secret
                key: db-connection-str
        
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 10

        startupProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
  # namespace: eventease
spec:
  type: ClusterIP
  selector:
    app: authservice
  ports:
  - name: authservice
    protocol: TCP
    port: 80
    targetPort: 80
