apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-depl
  # namespace: eventease
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/"
    prometheus.io/port: "80"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventservice
  template:
    metadata:
      labels:
        app: eventservice
    spec:
      containers:
      - name: eventservice
        image: oaddev/eventservice:d15726c98b8d3d8a65897506ef94995ea1fb3f09
        env:
          - name: RABBIT_MQ
            valueFrom:
              secretKeyRef:
                name: rabbit-mq-secret
                key: rabbit-mq
          - name: JWT
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwt
          - name: EVENT_DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: event-db-secret
                key: db-connection-str
---
apiVersion: v1
kind: Service
metadata:
  name: event-clusterip-srv
  # namespace: eventease
spec:
  type: ClusterIP
  selector:
    app: eventservice
  ports:
  - name: eventservice
    protocol: TCP
    port: 80
    targetPort: 80
