apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventservice
  template:
    metadata:
      labels:
        app: eventservice
    spec:
      containers:
      - name: eventservice
        image: oaddev/eventservice:aa58b399c9a012fde1092884e498b42500ee9f85
        env:
          - name: RABBIT_MQ
            valueFrom:
              secretKeyRef:
                name: rabbit-mq-secret
                key: rabbit-mq
          - name: JWT
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwt
          - name: EVENT_DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: event-db-secret
                key: db-connection-str
---
apiVersion: v1
kind: Service
metadata:
  name: event-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: eventservice
  ports:
  - name: eventservice
    protocol: TCP
    port: 80
    targetPort: 80
