apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: searchservice-hpa
  namespace: eventease
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-depl
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      # relative to the resource limits set for the containers
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50