apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchservice
  template:
    metadata:
      labels:
        app: searchservice
    spec:
      containers:
      - name: searchservice
        image: oaddev/searchservice
        env:
          - name: RABBIT_MQ
            valueFrom:
              secretKeyRef:
                name: rabbit-mq-secret
                key: rabbit-mq
          - name: JWT
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwt
          - name: SEARCH_DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: search-db-secret
                key: db-connection-str
          - name: SEARCH_DB_NAME
            valueFrom:
              secretKeyRef:
                name: search-db-secret
                key: db-name
          - name: EVENTS_COLLECTION_NAME
            valueFrom:
              secretKeyRef:
                name: search-db-secret
                key: events-collection-name
---
apiVersion: v1
kind: Service
metadata:
  name: search-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: searchservice
  ports:
  - name: searchservice
    protocol: TCP
    port: 80
    targetPort: 80