apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: searchservice-hpa
  namespace: eventease
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-depl
    # metrics: 50
  minReplicas: 1
  maxReplicas: 6   
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1