apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
  # namespace: eventease
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/"
    prometheus.io/port: "80"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: oaddev/userservice:d74ccd265b88a3aeef75a99a31750326dac8a0a5
        env:
          - name: RABBIT_MQ
            valueFrom:
              secretKeyRef:
                name: rabbit-mq-secret
                key: rabbit-mq
          - name: JWT
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: jwt
          - name: USER_DB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: user-db-secret
                key: db-connection-str
---
apiVersion: v1
kind: Service
metadata:
  name: user-clusterip-srv
  # namespace: eventease
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
  - name: userservice
    protocol: TCP
    port: 80
    targetPort: 80
